version: '3.3'

services:

  postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      # below the sql script for multiple dbs
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_DB: cataloguedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
  
  sebastian:
    container_name: sebastian
    build:
      context: .
      dockerfile: ./sebastian/Dockerfile
    ports:
    #validate this
      - 8082:8082
      #for debugging
      - 5005:5005
    volumes:
    # mount local application.properties file in the container: after modify it run sudo docker-compose restart sebastian
      - ./sebastian/sebastian_application.properties:/home/ubuntu/slicer/sebastian_application.properties
    # you should put vnfd and nsd descriptors in volumes/sebastian/ 
      - ./volumes/sebastian:/home/ubuntu/descriptors
    command: >
      bash -c "/usr/bin/java -jar /home/ubuntu/slicer/SEBASTIAN/SEBASTIAN_CORE/target/SebastianCore-0.0.2-SNAPSHOT.jar
      --spring.config.location=/home/ubuntu/slicer/sebastian_application.properties"
    depends_on: 
      - postgres
      - rabbitmq

  # Uncommnet to build the GUI
  #angular_gui:
  #  container_name: angular_gui
  #  build:
  #    context: .
  #    dockerfile: ./angular/Dockerfile
  #  ports:
  #    - 80:80
  #  depends_on: 
  #  - sebastian